# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tirith < Formula
  desc "AI API cost observability — one import, full transparency"
  homepage "https://github.com/joedaviesio/tirith"
  version "2.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joedaviesio/tirith/releases/download/v2.0.0/tirith_2.0.0_darwin_amd64.tar.gz"
      sha256 "366d2d3705b396c3355342b78e3e351985b3097f78d08e6845bd569b56ba55bf"

      define_method(:install) do
        bin.install "tirith"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joedaviesio/tirith/releases/download/v2.0.0/tirith_2.0.0_darwin_arm64.tar.gz"
      sha256 "a6b3101d9c9f02bb9395644b37b7b92af3cff24bf150ee4689061224050a2a9f"

      define_method(:install) do
        bin.install "tirith"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joedaviesio/tirith/releases/download/v2.0.0/tirith_2.0.0_linux_amd64.tar.gz"
      sha256 "ef4214ea8607253c0e28604e53fb3b22faa91c65ff796942a3a854858dc47c5a"
      define_method(:install) do
        bin.install "tirith"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joedaviesio/tirith/releases/download/v2.0.0/tirith_2.0.0_linux_arm64.tar.gz"
      sha256 "1c3abbc9e478a54b16e607e2b62e9397af956cf62b67c054a148992cc53ea503"
      define_method(:install) do
        bin.install "tirith"
      end
    end
  end

  test do
    assert_match "tirith", shell_output("#{bin}/tirith --version")
  end
end
