# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tirith < Formula
  desc "AI API cost observability — one import, full transparency"
  homepage "https://github.com/joedaviesio/tirith"
  version "2.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joedaviesio/tirith/releases/download/v2.1.0/tirith_2.1.0_darwin_amd64.tar.gz"
      sha256 "6f7a54424faa8acd39daa2d5714b6d454e2a6df28de2e668596eb554c9be6d41"

      define_method(:install) do
        bin.install "tirith"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joedaviesio/tirith/releases/download/v2.1.0/tirith_2.1.0_darwin_arm64.tar.gz"
      sha256 "1fbe8e11573097f431a4e1ffe6ded6f78b061a88ebb62b1a2551b6216d23b0ef"

      define_method(:install) do
        bin.install "tirith"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joedaviesio/tirith/releases/download/v2.1.0/tirith_2.1.0_linux_amd64.tar.gz"
      sha256 "b4ffe6cc7b6674e88dc2ac8a1a910f146c03cff4dcfbb4cdc3ead90be033d6fd"
      define_method(:install) do
        bin.install "tirith"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joedaviesio/tirith/releases/download/v2.1.0/tirith_2.1.0_linux_arm64.tar.gz"
      sha256 "21bf63db5f5d197e11bab2508c29d528d81546a3bdc206c6cb316ce95b197bb4"
      define_method(:install) do
        bin.install "tirith"
      end
    end
  end

  test do
    assert_match "tirith", shell_output("#{bin}/tirith --version")
  end
end
